### ISSUE TITLE
CachedWidgetWarning with CookieManager

### ISSUE THREAD

**Issue by oyarsa** [blipk/StreamlitExtras#10]
Example to reproduce:

```py
import extra_streamlit_components as stx
import streamlit as st


@st.cache_resource
def get_manager():
    return stx.CookieManager()


cookie_manager = get_manager()
```

Output:

```
CachedWidgetWarning: Your script uses a widget command in a cached function (function decorated with @st.cache_data or @st.cache_resource). This code will only be called when we detect a cache "miss", which can lead to unexpected results.

How to fix this:

    Move all widget commands outside the cached function.
    Or, if you know what you're doing, use experimental_allow_widgets=True in the cache decorator to enable widget replay and suppress this warning.

Traceback:

File "/Users/italo/.pyenv/versions/3.10.11/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
File "/Users/italo/.pyenv/versions/3.10.11/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
File "/Users/italo/.pyenv/versions/3.10.11/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
File "/Users/italo/dev/test.py", line 10, in <module>
    cookie_manager = get_manager()
File "/Users/italo/dev/test.py", line 7, in get_manager
    return stx.CookieManager()
File "/Users/italo/dev/.venv/lib/python3.10/site-packages/extra_streamlit_components/CookieManager/__init__.py", line 22, in __init__
    self.cookies = self.cookie_manager(method="getAll", key=key, default={})
```

Despite the warning, it seems to work correctly. However, adding the `experimental_allow_widgets=True` option in an attempt to suppress the warning breaks the cookies so that it resets on page refreshes.

Versions:

macOS: 14.4.1 (M1)
streamlit: 1.34.0
extra_streamlit_components: 0.1.71
Python: 3.10.11

**Comment by blipk** [comment]
@oyarsa 

`stx.CookieManager()` uses a Streamlit/React component that injects javascript to manage the cookies, you can't put this in a `@st.cache_resource` or otherwise, as it requires non-cached reactivity for cookie and component state syncronisation with the streamlit process.

**Comment by oyarsa** [comment]
So I just add the init code at the top of every page in the app? Or do I move it to a separate module and import that?

**Comment by blipk** [comment]
@oyarsa 

Anywhere it's instance will be unique for the streamlit user session - `delayed_init()` saves it's current class instance to the streamlit user session state.

At the top of each page works well, otherwise you have to manage dependency injection and keeping it at the root of your streamlit code anyway.

Avoid importing from modules can lead to a resource being cached between users or import issues.


EDIT: I could possible call `delayed_init()` in the `CookieManager` constructor or `get_cookie_manager()`, however I recall having issues with streamlit session state getting out of sync if called from there, thats why it's an additional function, and must be immediately after the `get_cookie_manager()` call, which in turn must not be cached because it's a reactive component.

**Comment by oyarsa** [comment]
I understand now. Thank you for your great work.
