### ISSUE TITLE
Set cookie bug

### ISSUE THREAD

**Issue by fabiogra** [blipk/StreamlitExtras#2]
Hello,
thank you for creating this project.

Description:

I tried this component in my project and I have noticed a bug when trying to set cookies. Specifically, when you try to set a cookie for the second time, the app will not stop running and I see continue reload in console logs.

I have also attached a minimal reproducible code snippet which demonstrate the issue.

To reproduce the bug, create a new Streamlit app that uses this component and run the following code:

```
import streamlit as st
from streamlitextras.cookiemanager import get_cookie_manager
from streamlitextras.logger import log
cookie_manager = None

def set_cookie(name, value):
    log.debug("Setting cookie")
    cookie_manager = get_cookie_manager()
    cookie_manager.delayed_init() # Makes sure CookieManager stays in st.session_state
    cookie_manager.set(name, value)

def main():
    global cookie_manager
    cookie_manager = get_cookie_manager()
    cookie_manager.delayed_init() # Makes sure CookieManager stays in st.session_state

    cookie_manager.set("my_cookie_name", "I'm a cookie!")
    my_cookie_value = cookie_manager.get("my_cookie_name")
    st.write(my_cookie_value) # "I'm a cookie"

    my_cookies = cookie_manager.get_all("my_cookie_name")
    st.write(my_cookies) # {"my_cookie_name": "I'm a cookie!"}

    cookie_manager.delete("my_cookie_name")
    my_cookie_value = cookie_manager.get("my_cookie_name")
    st.write(my_cookie_value) # None


if __name__ == "__main__":
    main()
    set_cookie("another cookie", "I'm a cookie!")
```

Expected behavior:

- The component should be able to properly set cookies as expected.

Actual behavior:

- The component is not properly setting cookies.

Environment:

- Python version: 3.10.8
- Streamlit version: 1.14.1
- streamlit-base-extras version: 0.2.13
- Operating system: Mac OS X 12.6

Please let me know if any more details are required. I would be happy to provide them.

**Comment by blipk** [comment]
Hi @fabiogra 

This is more of a streamlit bug, setting the component in the mainloop is going to cause a redraw, so it comes back and keeps going over and over again.

You also do not need to run `delayed_init()` more than once, nor keep assigning with `cookie_manager = get_cookie_manager()`

Something like below should work:
```python
import streamlit as st
from streamlitextras.cookiemanager import get_cookie_manager
from streamlitextras.logger import log
cookie_manager = None

def set_cookie(name, value):
    global cookie_manager
    log.debug("Setting cookie")
    cookie_manager.set(name, value)

def main():
    global cookie_manager
    cookie_manager = get_cookie_manager()
    cookie_manager.delayed_init() # Makes sure CookieManager stays in st.session_state

    my_cookies = cookie_manager.get_all()
    st.write(my_cookies)

    st.button("Set cookie", on_click=set_cookie, args=("another cookie", "I'm a cookie!",))


if __name__ == "__main__":
    main()
```

Admittedly though, it is buggy, streamlit doesn't deal well with invisible components and it runs them in an iframe so it can be hard to get the cookies into the parent scope.

I suggest trying it in a real example with real control flow, and it has generally worked for me.
If you run into any real usage problems, please open a specific issue, otherwise there's not much I can do to change the temperamental behaviour of streamlit.
