### ISSUE TITLE
Trouble Understanding Routing

### ISSUE THREAD

**Issue by evan-harley** [blipk/StreamlitExtras#5]
Good Morning,

I have been trying to use these components to build something like a multi page app. I appreciate the work that you have done to facilitate these sorts of things. The Authentication component is great. (With considerations given to the issue that I reported earlier.) I am just struggling to get the router to work correctly. 

I was building off of the example that you give using a routes folder. Which works for loading the landing page. But, when I try to route from that landing page anywhere else it doesn't seem to actually do anything. With the landing page loading immediately over the page that I am trying to route to.

Any help that you can offer would be appreciated.
Thank you,
Evan

**Comment by blipk** [comment]
Hey @evan-harley 

The example code is a bit old now and I have made some changes, didn't realise anyone was really using this besides myself.

You might need to pass the `rerun_st=True` argument to the router.route() function - depends if you're calling it from a callback or elsewhere.

Otherwise I might need some sample code and what you're trying to achieve to help you out.
